config/routes.rb
Rails.application.routes.draw do
  namespace :forest do
    post '/actions/publish-all' => 'races#publish_all'
    post '/actions/unpublish-all' => 'races#unpublish_all'
  end
  mount ForestLiana::Engine => '/forest'


  devise_for :users,
      controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :races, only: [:index, :show] do
    post 'like', to: 'races#like', as: :like
  end

  resources :races do
    resources :reviews, only: [ :create ]
  end

  get 'privacy', to: 'pages#privacy', as: :privacy
  get 'tos', to: 'pages#tos', as: :tos
  get 'dashboard', to: 'pages#dashboard', as: :dashboard
end

app/models/race.rb
class Race < ApplicationRecord
  include PgSearch
  multisearchable against: [ :name, :sport, :format, :address ]
  has_many :participations, dependent: :destroy
  has_many :reviews, dependent: :destroy
  mount_uploader :photo, PhotoUploader
  validates :address, presence: true
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  FORMATS_SPORTS = {
    "Triathlon" => ["Triathlon"],
    "Running" => ["Marathon", "Semi-marathon", "Course de 15km ou moins"]
    # "Cyclisme" => ["Autre"],
    # "Swimrun" => "Long",
  }

  validates :sport, inclusion: { in: FORMATS_SPORTS.keys, allow_blank: false }
  validate :format_consistent_with_sport
  acts_as_votable

  def format_consistent_with_sport
    if !(FORMATS_SPORTS[self.sport] || []).include?(self.format)
      errors.add(:format, "is not included in the list")
    end
  end

  def voters_excluding_self(user)
    get_likes.reject { |like| like.voter == user }.map {|like| like.voter }
  end

  def average_rating
    sum = 0
    reviews.each do |review|
      sum += review.score unless review.score.nil?
    end
    reviews.count == 0 ? 0 : sum.fdiv(reviews.count).to_i
  end
end

app/controllers/forest/races_controller.rb
# ForestLiana::ApplicationController takes care of the authentication for you.
class Forest::RacesController < ForestLiana::ApplicationController
  def publish_all
    # Your business logic to send an email here.
    @races = Race.all
    @races.each do |race|
      race.published = true
      race.save
    end
    head :no_content
  end
  def unpublish_all
    # Your business logic to send an email here.
    @races = Race.all
    @races.each do |race|
      race.published = false
      race.save
    end
    head :no_content
  end
end

app/controllers/races_controller.rb
class RacesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show, :like]
  skip_after_action :verify_policy_scoped, only: :index

  def index

    if params[:pg_search_documents].present?
      PgSearch::Multisearch.rebuild(Race)
      @races = PgSearch.multisearch(params[:pg_search_documents]).map { |doc| doc.searchable }
    else

      @races = policy_scope(Race.all)
      filters = {}
      # filters[:sport] = params[:sport] if params[:sport].present?
      filters[:format] = params[:format] if params[:format].present?
      @races = @races.where(filters)
      @races = @races.where("starts_at > ?", params[:from].split(" ").first) if params[:from].present?
      @races = @races.where("starts_at < ?", params[:from].split(" ").last) if params[:from].present?
     #@races = @races.near(params[:address] || "Bourges", params[:range] || 500) if params[:address].present?

      if params[:address].present? && params[:range].present?
        @races = @races.near(params[:address], params[:range])
      elsif params[:address].present?
        @races = @races.near(params[:address], 50)
      else
        @races = @races.near("Bourges", 1000)
      end
      @races = @races.where("available_slots > ?", params[:distance].split(",").first.to_i) if params[:distance].present?
      @races = @races.where("available_slots < ?", params[:distance].split(",").last.to_i) if params[:distance].present?
      # @races = @races.where(published: true) # only show races that have been published
      # @races = @races.where("starts_at >= ?", Date.today) # only show races in the future
      @races = @races.order(starts_at: :asc)
      # @races = params[:page] ? @races : @races.page(params[:page])
      @races = @races.page(params[:page] || 1)
    end


    @format = params[:format] if params[:format].present?
    @address = params[:address] if params[:address].present?
    @range = params[:range] if params[:range].present?
    @from = params[:from] if params[:from].present?
    # @minp = params[:distance].split(",").first.to_i if params[:distance].present?
    # @maxp = params[:distance].split(",").last.to_i if params[:distance].present?

    @markers = @races.map do |race|
      next if race.latitude.nil?
        {
          lat: race.latitude,
          lng: race.longitude,
          icon: helpers.asset_path("flag.png"),
          infoWindow: { content: render_to_string(partial: "/races/map_box", locals: { race: race }) }
        }
    end
    @markers = @markers.compact
  end

  def show
    # @race = policy_scope(Race.find(params[:id]))
    @review = Review.new
    @race = Race.find(params[:id])
    authorize @race
  end

  def like
    # si pas connecté
    if user_signed_in? == false
    # stocker en session l'id de la race à liker
      @race = Race.find(params[:race_id])
      authorize @race
      session[:liked_race_id] = @race.id
      # loguer redirect_to new_user_session_path
      redirect_to new_user_session_path
    # sinon
    else
      @race = Race.find(params[:race_id])
      authorize @race
      if current_user.voted_for?(@race)
        @race.unliked_by current_user
        p current_user.voted_for?(@race)
      else
        @race.liked_by(current_user)
      end
      respond_to do |format|
        format.html { redirect_to stored_location_for(:user) }
        format.js
      end

    end
  end
end

app/views/races/_card.html.erb
<div class="card" data-race-id="<%= race.id %>">
  <%= link_to "", race_path(race), class: "card-link"%>
  <div class="card-picture" style="background-image: linear-gradient(270deg, rgba(0,0,0,0.4), rgba(0,0,0,0.4)), url(<%= race.image_race.nil? ? race.photo : race.image_race %>);">
    <div class="card-format">
        <div class="card-top">
          <div class="card-sport">
            <%= race.format %>
          </div>
          <br>
          <div class="card-date">
            <%= race.starts_at.strftime("%d-%b-%y") if race.starts_at %>
          </div>
        </div>
      <div class="card-btn-top-right">
        <% if current_user != nil and current_user.voted_for? race and race.starts_at != nil and race.starts_at < Date.today %>
          <div class="card-review">
            <%= link_to race_path(race, anchor: "show-redirection") do |f| %>
              <%= button_tag type: "submit", class: "like-button-form" do %>
              <img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAHWSURBVDhPzZPPK0RRFMcfQjZ+z7w7Y2LDRiykkObemzGFP2CWLKxspBRLCzsLpWShsSSRlUix8aOUFUox/8Pkx7w3lp7vuR3FeM+PZsGnXu+ec+/9nnPPudf6c3IR3ejacpHN4vCsVJljywM3IofYVRx5ISdcIbfYLA43pAXEDpHhJQmz+3voWI/N8bp8Q3/UsXWHI3TKESqNup3lIkp67e0VEN0vFPUsq5SHH3GFGnFtlcG3A6E1fNN5O97L04ZCUewZw7oLX1FHyAUnHB9kM5CXWF8Vss6SEMRXs/U91Tz1EWR2/NI6XMmmOcqzGGgpjO7Yah6ZzT2FZD+7PvPQomsRcY9NAxqxba4K/ux6u4unCFLCLn+4AdNsGpDFjemwre7YZTlhNQV7nM1gkMUGFneyiY06iQBX8B9RMHZTWdafGlUbm/54Vnc5srl+OwaLXeREPGQWvAONO6frxaY/qFMCmSyZ8RdiBM3xMBgUeSUnpAoSoy67UdWF485i7S27/aHFyPCSHv17sXws0UTFRyk28T+moKZx4YRtNgYBAU1RSYxeBcYzEDhBCfB29STdQ176M5DBMj4PIhkUfNcVepTuJE//DuoqMkuTyH1dsobd/wXLegUm+dVJCS2LsgAAAABJRU5ErkJggg==">

              <% end %>
            <% end %>
            <%# link_to race_like_path(race) do %>
            <%# end %>
          </div>
        <% end %>
        <div class="card-wishlist">
          <%= form_for race, url: race_like_path(race), method: :post, remote: true do |f| %>
            <%= button_tag type: "submit", class: "like-button-form" do %>
              <i class="<%= current_user && current_user.voted_for?(race) ? "fas" : "far" %> fa-heart"></i>
            <% end %>
          <% end %>
          <%# link_to race_like_path(race) do %>
          <%# end %>
        </div>
      </div>

    </div>
    <div class="card-bottom">
      <div class="card-name">
        <strong><%= race.name %></strong>
      </div>
    </div>
      <div class="card-participants">
        <%= race.available_slots.nil? ? "" : "#{race.available_slots} participants"  %>
      </div>
  </div>
  <div class="card-description">
    <div class="card-friends" >
      <% voters = race.voters_excluding_self(current_user) %>
      <% voters.each do |user| %>
        <% if user.facebook_picture_url %>
          <%= image_tag user.facebook_picture_url, class: "card-avatar" %>
        <% else %>
          <%= image_tag "runner.jpg", class: "card-avatar" %>
        <% end %>
      <% end %>
     <p class="card-avatar-text"> <%= voters.size < 2 ? "#{voters.size} ami" : "#{voters.size} amis" %> </p>
    </div>
  </div>
</div>

app/views/races/_map_box.html.erb
<strong>
  <%= race.name %>
</strong>

app/views/races/_races.html.erb
<% races.each do |race| %>
  <%= render "races/card", race: race %>
<% end %>

app/views/races/index.html.erb
<div class="container-fluid">
  <div class="searchbar">
    <%= form_tag(races_path, method: :get) do %>
    <%= text_field_tag :pg_search_documents , nil, class: "drop", placeholder: "Search" %>
    <% end %>
  </div>
  <div class="index-container">

    <div class="left-container">
      <div class="card-container">
        <button class="plusdefiltre btn-default dropdown-toggle" role="button" data-toggle="collapse" href="#collapseExample" aria-expanded="true" aria-controls="collapseExample">
          Plus de filtres
          <span class="caret"></span>
        </button>
        <div class="collapse" id="collapseExample">
          <div class="well">
            <div class="filters">
              <%= form_tag(races_path, method: :get, :class =>'filter-form') do %>
              <h4>Mon épreuve</h4>
              <div class="index-inputs">
                  <%= select_tag :format, options_for_select(Race::FORMATS_SPORTS.values.flatten, @format), {class: 'index-drop'}%>
                  <%= select_tag :range, options_for_select([["jusqu'à 50km de", "50"], ["jusqu'à 200km de", "200"], ["jusqu'à 1000km de", "1000"]], @range), {class: 'index-drop'} %><%= text_field_tag :address, @address, class: "index-drop", placeholder: @address %>
              </div>
              <h4>Mes disponibilités</h4>
              <div class="index-inputs">
                <%= text_field_tag :from, @from, id: "range_start", class: "datepicker index-drop" %>
              </div>
              <h4>Nombre de participants</h4>
              <div class="slider-distance">
                <b>10</b>
                <input id="ex2" type="text" class="span2" name="distance" value="" data-slider-min="10" data-slider-max="40000" data-slider-step="5" data-slider-value="[1,40000]"/>
                 <b>40000</b>
              </div>
              <div class="index-inputs">
                <%= submit_tag "Appliquer les filtres", name: nil, class: 'plusdefiltre' %>
              </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
      <div class= "resultats">
        <p>
          <%= ( @races.length == 1 || @races.length == 0 ) ? "#{@races.length} résultat : cliquez sur \"Plus de filtres\" pour élargir votre recherche !" : "#{@races.length} résultats" %>
        </p>
      </div>
      <div class="races">
        <%= render "races", races: @races %>
      </div>
      <hr />
   </div>
   <div id="map" class="hidden-sm" data-markers="<%= @markers.to_json %>" data-icon-path="<%= asset_path 'flag.png' %>"></div>
  </div>
  <div class="pages">
    <!-- rajoute condition if params de page/ -->
    <% unless params[:pg_search_documents] %>
      <%= paginate @races, remote: true%>
    <% end %>
    <%= page_entries_info @races if params[:page] %>
  </div>
  </div>
</div>

app/views/races/index.js.erb
// app/views/races/index.js.erb

function updateRaces(racesHTML, pagesHTML) {
  const races = document.querySelector('.races');
  races.insertAdjacentHTML('beforeend', racesHTML);

  const pages = document.querySelector('.pages');
  pages.innerHTML = pagesHTML;
}

updateRaces(
  '<%= j render "races", races: @races %>',
  '<%= j paginate(@races, remote: true).to_s %>'
);

app/views/races/like.js.erb
function whishlist() {
  const card = document.querySelector("[data-race-id='<%= @race.id%>']");
  card.outerHTML = "<%= j render 'races/card', race: @race %>";
}

function removeCard() {
  const card = document.querySelector("[data-race-id='<%= @race.id%>']");
  card.remove();
}

<% if request.referer.include?('dashboard') %>
  removeCard();
<% else %>
  whishlist();
<% end %>

app/views/races/new.html.erb
<div class="banner-new" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('http://acm-sport.com/wp-content/uploads/2017/05/picture1-ok-.jpg');">
  <div class="new-form-container">
    <h2>Create your race</h2>
    <br>
    <%= simple_form_for(@product) do |f| %>
      <div class="form-inputs">
        <%= f.input :title, required: true%>
        <%= f.input :category, collection: Product::CATEGORY_COLORS.keys, required: true %>
        <%= f.input :price_per_day, required: true %>
        <%= f.input :address, input_html: { class: "autocomplete", required: true } %>
        <%= f.input :description, required: true %>
        <%= f.input :photo%>
        <%= f.input :photo_cache, as: :hidden%>
        <br>
      </div>

      <div class="form-actions">
        <%= f.button :submit, "Post your ad", class: "btn btn-primary full-width" %>
      </div>

    <% end %>
  </div>
</div>