config/routes.rb
Rails.application.routes.draw do
  namespace :forest do
    post '/actions/publish-all' => 'races#publish_all'
    post '/actions/unpublish-all' => 'races#unpublish_all'
  end
  mount ForestLiana::Engine => '/forest'


  devise_for :users,
      controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :races, only: [:index, :show] do
    post 'like', to: 'races#like', as: :like
  end

  resources :races do
    resources :reviews, only: [ :create ]
  end

  get 'privacy', to: 'pages#privacy', as: :privacy
  get 'tos', to: 'pages#tos', as: :tos
  get 'dashboard', to: 'pages#dashboard', as: :dashboard
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon <%= yield(:navbar_class) %>">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png", height: 50 %>
  <% end %>
  <div class="navbar-search">
    <div class="searchbar">
      <%= form_tag(races_path, method: :get) do %>
      <%= text_field_tag :pg_search_documents , nil, class: "drop-searchbar", placeholder: "Marathon? Paris? 25 juillet?" %>
      <%= submit_tag "Go", name: nil, class: 'btn-go-searchbar' %>
      <% end %>
    </div>

  </div>
  <!-- Right Navigation -->
  <div class="navbar-right">
    <div class="search navbar-wagon-item navbar-wagon-link" id="search-item">
      <i class="fas fa-search"></i>
    </div>
    <div class="navbar-wagon-right hidden-xs hidden-sm">

      <% if user_signed_in? %>

        <!-- Links when logged in -->
        <%#= link_to "Create a race", new_race_path, class: "navbar-wagon-item navbar-wagon-link" %>

        <%= link_to "Ma liste", dashboard_path, class: "navbar-wagon-item navbar-wagon-link" %>

        <!-- Avatar with dropdown menu -->
        <div>
          <div class="dropdown">
            <% avatar_url = current_user.facebook_picture_url || "http://placehold.it/30x30" %>
            <%= image_tag avatar_url, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
            <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
              <li>
                <%= link_to "#" do %>
                  <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
                <% end %>
              </li>
              <li>
                <%= link_to "#" do %>
                  <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
                <% end %>
              </li>
              <li>
                <%= link_to destroy_user_session_path, method: :delete do %>
                  <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
                <% end %>
              </li>
            </ul>
          </div>
        </div>
      <% else %>
        <!-- Login link (when logged out) -->
        <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <% end %>
    </div>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle navbar-wagon-link" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><%= link_to "Ma liste", dashboard_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_searchbar.html.erb
<div class="searchbar" >
  <%= form_tag(races_path, method: :get) do %>
    <%= text_field_tag :pg_search_documents , nil, class: "drop-searchbar", placeholder: "Search" %>
    <%= submit_tag "Go", name: nil, class: 'btn-go-searchbar' %>
  <% end %>
</div>